//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageCropResize {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Preset 1")]
        public string Preset1_Name {
            get {
                return ((string)(this["Preset1_Name"]));
            }
            set {
                this["Preset1_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset1_XValue {
            get {
                return ((int)(this["Preset1_XValue"]));
            }
            set {
                this["Preset1_XValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset1_YValue {
            get {
                return ((int)(this["Preset1_YValue"]));
            }
            set {
                this["Preset1_YValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset1_Width {
            get {
                return ((int)(this["Preset1_Width"]));
            }
            set {
                this["Preset1_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset1_Height {
            get {
                return ((int)(this["Preset1_Height"]));
            }
            set {
                this["Preset1_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Preset 2")]
        public string Preset2_Name {
            get {
                return ((string)(this["Preset2_Name"]));
            }
            set {
                this["Preset2_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset2_XValue {
            get {
                return ((int)(this["Preset2_XValue"]));
            }
            set {
                this["Preset2_XValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset2_YValue {
            get {
                return ((int)(this["Preset2_YValue"]));
            }
            set {
                this["Preset2_YValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset2_Width {
            get {
                return ((int)(this["Preset2_Width"]));
            }
            set {
                this["Preset2_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset2_Height {
            get {
                return ((int)(this["Preset2_Height"]));
            }
            set {
                this["Preset2_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Preset 3")]
        public string Preset3_Name {
            get {
                return ((string)(this["Preset3_Name"]));
            }
            set {
                this["Preset3_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset3_XValue {
            get {
                return ((int)(this["Preset3_XValue"]));
            }
            set {
                this["Preset3_XValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset3_YValue {
            get {
                return ((int)(this["Preset3_YValue"]));
            }
            set {
                this["Preset3_YValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset3_Width {
            get {
                return ((int)(this["Preset3_Width"]));
            }
            set {
                this["Preset3_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset3_Height {
            get {
                return ((int)(this["Preset3_Height"]));
            }
            set {
                this["Preset3_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset1_ResizeWidth {
            get {
                return ((int)(this["Preset1_ResizeWidth"]));
            }
            set {
                this["Preset1_ResizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset1_ResizeHeight {
            get {
                return ((int)(this["Preset1_ResizeHeight"]));
            }
            set {
                this["Preset1_ResizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset2_ResizeWidth {
            get {
                return ((int)(this["Preset2_ResizeWidth"]));
            }
            set {
                this["Preset2_ResizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset2_ResizeHeight {
            get {
                return ((int)(this["Preset2_ResizeHeight"]));
            }
            set {
                this["Preset2_ResizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset3_ResizeWidth {
            get {
                return ((int)(this["Preset3_ResizeWidth"]));
            }
            set {
                this["Preset3_ResizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Preset3_ResizeHeight {
            get {
                return ((int)(this["Preset3_ResizeHeight"]));
            }
            set {
                this["Preset3_ResizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Preset1_ResizeEnabled {
            get {
                return ((bool)(this["Preset1_ResizeEnabled"]));
            }
            set {
                this["Preset1_ResizeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Preset2_ResizeEnabled {
            get {
                return ((bool)(this["Preset2_ResizeEnabled"]));
            }
            set {
                this["Preset2_ResizeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Preset3_ResizeEnabled {
            get {
                return ((bool)(this["Preset3_ResizeEnabled"]));
            }
            set {
                this["Preset3_ResizeEnabled"] = value;
            }
        }
    }
}
